version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/solutions/motion-project-solutions/backend:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: '/usr/sbin/sshd -D'
    ports:
      - '8000:8000'
      - '4777:22'
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files

  email:
    image: registry.gitlab.propulsion-home.ch/full-stack/solutions/motion-project-solutions/backend:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'python manage.py send_mail'
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    depends_on:
      - postgres
      - backend


volumes:
  postgres:
  media-files:
  static-files:
