# Generated by Django 2.2.2 on 2019-11-25 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_auto_20191112_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, verbose_name='keyword')),
                ('user', models.ManyToManyField(related_name='things_user_likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
