export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const VERIFICATION_ERROR = 'VERIFICATION_ERROR';

export const STORE_POSTS = 'STORE_POSTS';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';
export const FEED_ERROR = 'FEED_ERROR';
export const ADD_POST_TO_LIST = 'ADD_POST_TO_LIST';
export const DELETE_POST = 'DELETE_POST';
export const LIKE_POST = 'LIKE_POST';


export const GENERAL_ERROR = 'NETWORK_ERROR';
export const GENERAL_ERROR_CLEAR = 'GENERAL_ERROR_CLEAR';

export const STORE_USERS = 'STORE_USERS';
export const USERS_ERROR = 'USERS_ERROR';

// USER PROFILE
export const STORE_MY_PROFILE_DATA = 'STORE_MY_PROFILE_DATA';
export const SET_MY_PROFILE_ACTIVE_TAB = 'SET_MY_PROFILE_ACTIVE_TAB';
export const MY_PROFILE_ERROR = 'MY_PROFILE_ERROR';

// MODAL
export const SET_MODAL = 'SET_MODAL';

